---
# Firewall deployment using Proxmox API
# No SSH/pct commands - fully declarative

- name: Create firewall container via Proxmox API
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_api_validate_certs }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ firewall_container_id }}"
    hostname: "{{ firewall_hostname }}"
    ostemplate: "local:vztmpl/{{ firewall_template_file | basename }}"
    cores: "{{ firewall_cores }}"
    memory: "{{ firewall_memory }}"
    swap: "{{ firewall_swap }}"
    disk: "{{ firewall_rootfs_storage }}:{{ firewall_disk }}"
    netif:
      net0: "name={{ firewall_wan_interface }},bridge={{ firewall_bridge_wan }},ip=manual,type=veth"
      net1: "name={{ firewall_lan_interface }},bridge={{ firewall_bridge_lan }},ip={{ firewall_lan_ip_address }}/{{ firewall_lan_prefix }},type=veth"
    unprivileged: "{{ firewall_unprivileged }}"
    onboot: true
    password: "{{ firewall_root_password }}"
    pubkey: "{{ proxmox_root_authorized_keys | join('\n') }}"
    state: present
  register: firewall_container

- name: Start firewall container via Proxmox API
  community.proxmox.proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    validate_certs: "{{ proxmox_api_validate_certs }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ firewall_container_id }}"
    hostname: "{{ firewall_hostname }}"
    state: started

- name: Wait for firewall container SSH to be available
  ansible.builtin.wait_for:
    host: "{{ firewall_lan_ip_address }}"
    port: 22
    delay: 10
    timeout: 120
    state: started

- name: Add firewall to in-memory inventory for delegation
  ansible.builtin.add_host:
    name: firewall_container
    ansible_host: "{{ firewall_lan_ip_address }}"
    ansible_user: root
    ansible_password: "{{ firewall_root_password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q root@{{ ansible_host }}"'
    groups: containers

# Configuration using delegation - NO pct exec!
- name: Install firewall packages
  ansible.builtin.apt:
    name: "{{ firewall_packages }}"
    state: present
    update_cache: true
  delegate_to: firewall_container

- name: Configure IP forwarding
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-firewall.conf
    reload: true
    state: present
  loop:
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "{{ 1 if firewall_enable_ipv6 else 0 }}" }
  delegate_to: firewall_container

- name: Configure nftables firewall rules
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  delegate_to: firewall_container
  notify: Restart nftables

- name: Configure WAN interface for DHCP on boot
  ansible.builtin.copy:
    content: |
      auto {{ firewall_wan_interface }}
      iface {{ firewall_wan_interface }} inet dhcp
    dest: "/etc/network/interfaces.d/{{ firewall_wan_interface }}"
    owner: root
    group: root
    mode: '0644'
  delegate_to: firewall_container

- name: Enable nftables service
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
  delegate_to: firewall_container

- name: Enable SSH service
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: started
  delegate_to: firewall_container

- name: Bring up WAN interface and get DHCP lease
  ansible.builtin.shell: |
    ifup {{ firewall_wan_interface }} || true
    dhclient {{ firewall_wan_interface }} || true
  delegate_to: firewall_container
  changed_when: false

- name: Get firewall WAN IP
  ansible.builtin.shell: |
    ip -4 addr show dev {{ firewall_wan_interface }} scope global | grep inet | awk '{print $2}' | cut -d/ -f1
  delegate_to: firewall_container
  register: firewall_wan_ip_result
  changed_when: false

- name: Display firewall configuration
  ansible.builtin.debug:
    msg:
      - "Firewall deployed successfully"
      - "  Container ID: {{ firewall_container_id }}"
      - "  WAN IP: {{ firewall_wan_ip_result.stdout | default('DHCP pending') }}"
      - "  DMZ IP: {{ firewall_lan_ip_address }}"
      - "  Hostname: {{ firewall_hostname }}"
