---
zabbix_container_id: 61
zabbix_hostname: zabbix
zabbix_domain: viljo.se
zabbix_memory: 8192
zabbix_cores: 4
zabbix_disk: 128
zabbix_swap: 2048
zabbix_bridge: "{{ public_bridge | default('vmbr3') }}"
zabbix_ip_address: 172.16.10.61
zabbix_netmask: 24
zabbix_ip_config: "{{ zabbix_ip_address }}/{{ zabbix_netmask }}"
zabbix_vlan_tag: null
zabbix_gateway: 172.16.10.1
zabbix_dns_servers:
  - 172.16.10.1
  - 1.1.1.1
zabbix_rootfs_storage: local-lvm
zabbix_unprivileged: true
zabbix_start_onboot: true
zabbix_features:
  nesting: 1
zabbix_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
zabbix_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"
zabbix_root_password: "{{ vault_zabbix_root_password | default('') }}"
zabbix_rootfs_path: "/var/lib/lxc/{{ zabbix_container_id }}/rootfs"

# Zabbix version
zabbix_version_major: 7
zabbix_version_minor: 0
zabbix_version: "{{ zabbix_version_major }}.{{ zabbix_version_minor }}"
zabbix_repo_release: bookworm

# Database configuration (using shared PostgreSQL container)
zabbix_db_host: 172.16.10.50
zabbix_db_port: 5432
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: "{{ vault_zabbix_db_password | default('changeme') }}"

# Zabbix server configuration
zabbix_server_name: "Proxmox Infrastructure"
zabbix_server_port: 10051
zabbix_listen_ip: "0.0.0.0"
zabbix_housekeeping_frequency: 1
zabbix_history_storage_days: 365
zabbix_trends_storage_days: 730

# Web interface configuration
zabbix_web_server: apache2
zabbix_web_port: 80
zabbix_php_timezone: UTC
zabbix_external_domain: "{{ loopia_dns_domain | default(zabbix_domain) }}"
zabbix_admin_password: "{{ vault_zabbix_admin_password | default('zabbix') }}"

# Monitoring configuration
zabbix_enable_snmp: true
zabbix_enable_ipmi: false
zabbix_enable_java_gateway: false

# Agent configuration for monitoring other containers
zabbix_agent_port: 10050
zabbix_monitored_containers:
  - id: "{{ postgres_container_id | default(50) }}"
    name: PostgreSQL
    ip: 172.16.10.50
    templates:
      - Linux by Zabbix agent
      - PostgreSQL by Zabbix agent
  - id: "{{ jellyfin_container_id | default(56) }}"
    name: Jellyfin
    ip: 172.16.10.56
    templates:
      - Linux by Zabbix agent
      - HTTP Service
  - id: "{{ ha_container_id | default(57) }}"
    name: Home Assistant
    ip: 172.16.10.57
    templates:
      - Linux by Zabbix agent
      - HTTP Service
  - id: "{{ demo_site_container_id | default(60) }}"
    name: Demo Site
    ip: 172.16.10.60
    templates:
      - Linux by Zabbix agent
      - Nginx by Zabbix agent
  - id: "{{ omv_container_id | default(64) }}"
    name: OpenMediaVault
    ip: 172.16.10.64
    templates:
      - Linux by Zabbix agent
      - HTTP Service
  - id: "{{ zipline_container_id | default(65) }}"
    name: Zipline
    ip: 172.16.10.65
    templates:
      - Linux by Zabbix agent
      - HTTP Service
  - id: 1
    name: Firewall
    ip: 172.16.10.1
    templates:
      - Linux by Zabbix agent

# Dashboard configuration
zabbix_create_dashboards: true
zabbix_dashboard_refresh: 30s

# Alert configuration
zabbix_enable_email_alerts: false
zabbix_smtp_server: ""
zabbix_smtp_port: 25
zabbix_smtp_from: "zabbix@{{ public_domain }}"
zabbix_alert_recipients: []
