# Traefik Docker Labels Contract
# Purpose: Define Traefik routing configuration via Docker labels for webtop container
# Version: 1.0.0
# Date: 2025-10-20

---
# These labels are applied to the webtop Docker container to enable automatic
# service discovery and routing by Traefik reverse proxy

labels:
  # Enable Traefik management of this container
  traefik.enable: "true"

  # HTTP Router Configuration
  traefik.http.routers.webtop.rule: "Host(`browser.viljo.se`)"
  traefik.http.routers.webtop.entrypoints: "websecure"
  traefik.http.routers.webtop.tls: "true"
  traefik.http.routers.webtop.tls.certresolver: "letsencrypt"

  # Service Configuration
  traefik.http.services.webtop.loadbalancer.server.port: "3000"
  traefik.http.services.webtop.loadbalancer.server.scheme: "http"

  # Middleware (optional - for HTTPS redirect)
  traefik.http.middlewares.webtop-redirect.redirectscheme.scheme: "https"
  traefik.http.middlewares.webtop-redirect.redirectscheme.permanent: "true"

  # HTTP Router for redirect (port 80)
  traefik.http.routers.webtop-http.rule: "Host(`browser.viljo.se`)"
  traefik.http.routers.webtop-http.entrypoints: "web"
  traefik.http.routers.webtop-http.middlewares: "webtop-redirect"

# Contract Requirements:
# 1. Traefik must have access to Docker socket to read labels
# 2. DNS A record for browser.viljo.se must point to Traefik/firewall public IP
# 3. Traefik entrypoints "web" (80) and "websecure" (443) must be configured
# 4. Let's Encrypt cert resolver "letsencrypt" must be configured in Traefik static config
# 5. Firewall must forward ports 80/443 to Traefik

# Expected Behavior:
# - HTTP requests to browser.viljo.se redirect to HTTPS
# - HTTPS requests route to webtop container port 3000
# - Traefik automatically provisions and renews Let's Encrypt certificate
# - Health checks performed on port 3000 by Traefik

# Validation:
# - curl -I http://browser.viljo.se → 301/302 redirect to HTTPS
# - curl -I https://browser.viljo.se → 200 OK with valid TLS cert
# - Certificate issued by Let's Encrypt (check cert chain)
