---
# Keycloak SSO/Identity Provider deployment via Proxmox API

# Container configuration
keycloak_container_id: 151
keycloak_hostname: "keycloak"
keycloak_template_file: "debian-13-standard_13.1-2_amd64.tar.zst"
keycloak_external_domain: "viljo.se"

# Resources
keycloak_cores: 4
keycloak_memory: 4096
keycloak_swap: 1024
keycloak_disk: "40"
keycloak_rootfs_storage: "local-lvm"

# Network
keycloak_bridge: "vmbr3"
keycloak_ip_address: "172.16.10.151"
keycloak_netmask: "24"
keycloak_gateway: "172.16.10.101"
keycloak_dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"

# Container settings
keycloak_unprivileged: false
keycloak_features: "nesting=1"

# Keycloak configuration
keycloak_version: "24.0.3"
keycloak_service_port: 8080
keycloak_data_dir: "/opt/keycloak"
keycloak_compose_file: "/opt/keycloak/docker-compose.yml"

# Database configuration
keycloak_db_vendor: "postgres"
keycloak_db_host: "172.16.10.150"
keycloak_db_port: 5432
keycloak_db_name: "keycloak"
keycloak_db_user: "keycloak"
keycloak_db_password: "{{ vault_postgres_keycloak_password }}"

# Admin credentials
keycloak_admin_user: "admin"
keycloak_admin_password: "{{ vault_keycloak_admin_password }}"

# Passwords (from vault)
keycloak_root_password: "{{ vault_keycloak_root_password }}"
