---
# =============================================================================
# Home Assistant Supervised - Default Variables
# =============================================================================
# Configuration for Home Assistant Supervised deployment in LXC container
# with Docker support for add-ons.
#
# References:
#   - Spec: specs/active/009-home-assistant-supervised/spec.md
#   - ADR: docs/adr/002-container-id-standardization.md
#   - Container Mapping: docs/architecture/container-mapping.md
# =============================================================================

# -----------------------------------------------------------------------------
# Container Identification
# -----------------------------------------------------------------------------
# Container ID standardized per ADR-002: .57 = IoT mnemonic
ha_container_id: 57
ha_hostname: homeassistant
ha_domain: infra.local

# -----------------------------------------------------------------------------
# Container Resources
# -----------------------------------------------------------------------------
# Increased resources for Docker and Home Assistant Supervisor
# Minimum: 2GB RAM, 2 cores, 32GB disk
# Recommended: 4GB RAM, 4 cores, 64GB disk for multiple add-ons
ha_memory: 4096
ha_cores: 4
ha_disk: 64
ha_swap: 2048

# -----------------------------------------------------------------------------
# Container Network Configuration
# -----------------------------------------------------------------------------
ha_bridge: "{{ management_bridge | default('vmbr2') }}"
ha_ip_config: "172.16.10.57/24"
ha_vlan_tag: null
ha_gateway: "172.16.10.1"
ha_dns_servers:
  - "172.16.10.1"
  - "1.1.1.1"

# -----------------------------------------------------------------------------
# Container Storage and Template
# -----------------------------------------------------------------------------
ha_rootfs_storage: local-lvm

# IMPORTANT: Home Assistant Supervised requires Debian 12 (Bookworm)
# Debian 13 is NOT yet supported by the official installer
ha_template_url: "http://download.proxmox.com/images/system/debian-12-standard_12.7-1_amd64.tar.zst"
ha_template_file: "/var/lib/vz/template/cache/debian-12-standard_12.7-1_amd64.tar.zst"

# -----------------------------------------------------------------------------
# Container Security and Features
# -----------------------------------------------------------------------------
# SECURITY NOTE: Container must be privileged for Docker support
# This is a known trade-off for running Docker in LXC
# See: https://pve.proxmox.com/wiki/Linux_Container#pct_container_features
ha_unprivileged: false  # Must be false (privileged) for Docker
ha_start_onboot: true

# Nesting is required for Docker container support
# This is set explicitly in tasks and not configurable
# ha_features:
#   nesting: 1

# -----------------------------------------------------------------------------
# Container Access
# -----------------------------------------------------------------------------
ha_root_password: "{{ vault_homeassistant_root_password | default('') }}"
ha_rootfs_path: "/var/lib/lxc/{{ ha_container_id }}/rootfs"

# -----------------------------------------------------------------------------
# Home Assistant Supervised Configuration
# -----------------------------------------------------------------------------
# Service port for Home Assistant web interface
ha_service_port: 8123

# Public hostname for Traefik routing
ha_public_hostname: "ha.viljo.se"

# Home Assistant Supervised installer URL
# Latest version from: https://github.com/home-assistant/supervised-installer/releases
ha_supervised_installer_url: "https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb"

# Installation machine type (determines available add-ons)
# Options: generic-x86-64, odroid-c2, odroid-c4, odroid-n2, odroid-xu, qemuarm,
#          qemuarm-64, qemux86, qemux86-64, raspberrypi, raspberrypi2,
#          raspberrypi3, raspberrypi4, raspberrypi3-64, raspberrypi4-64, tinker
# For LXC containers on x86_64, use: qemux86-64
ha_machine_type: "qemux86-64"

# -----------------------------------------------------------------------------
# Data Persistence
# -----------------------------------------------------------------------------
# Home Assistant Supervised stores all data in /usr/share/hassio
# This includes:
#   - Home Assistant configuration
#   - Supervisor configuration
#   - Add-on data and configuration
#   - Backups
#   - Docker volumes for all components
#
# No custom paths needed - managed by Supervisor

# -----------------------------------------------------------------------------
# REMOVED VARIABLES (from Home Assistant Core implementation)
# -----------------------------------------------------------------------------
# The following variables are no longer used with Supervised installation:
#   - ha_user: Not needed (managed by Supervisor)
#   - ha_group: Not needed (managed by Supervisor)
#   - ha_install_dir: Not configurable (uses /usr/share/hassio)
#   - ha_venv_python: Not used (Docker-based)
#   - ha_venv_path: Not used (Docker-based)
#   - ha_config_dir: Not configurable (uses /usr/share/hassio/homeassistant)
#   - ha_extra_requirements: Not applicable (use add-ons instead)
# =============================================================================
