---
# Infrastructure Backup Configuration

# Backup destination
backup_storage: "local"  # Proxmox storage for container backups
backup_base_dir: "/var/backups/infrastructure"
backup_remote_enabled: false
backup_remote_host: ""
backup_remote_user: "backup"
backup_remote_path: "/backup/proxmox"

# Timestamp format for backups
backup_timestamp: "{{ ansible_date_time.iso8601_basic_short }}"

# Retention policy (days)
backup_retention_daily: 7
backup_retention_weekly: 4
backup_retention_monthly: 3

# Container backup configuration
backup_containers:
  - id: 101
    name: firewall
    enabled: true
    compress: true
  - id: 110
    name: bastion
    enabled: true
    compress: true
  - id: 150
    name: postgresql
    enabled: true
    compress: true
    stop_before_backup: false
  - id: 151
    name: keycloak
    enabled: true
    compress: true
  - id: 153
    name: gitlab
    enabled: true
    compress: true
  - id: 154
    name: gitlab-runner
    enabled: true
    compress: true
  - id: 155
    name: nextcloud
    enabled: true
    compress: true
  - id: 158
    name: redis
    enabled: true
    compress: true
  - id: 160
    name: demo-site
    enabled: true
    compress: true
  - id: 163
    name: mattermost
    enabled: true
    compress: true
  - id: 170
    name: webtop
    enabled: true
    compress: true

# PostgreSQL backup configuration
backup_postgresql_enabled: true
backup_postgresql_host: "172.16.10.150"
backup_postgresql_port: 5432
backup_postgresql_user: "postgres"
backup_postgresql_password: "{{ vault_postgres_user_password }}"
backup_postgresql_databases:
  - keycloak
  - gitlab
  - nextcloud
  - mattermost

# Redis backup configuration
backup_redis_enabled: true
backup_redis_host: "172.16.10.158"
backup_redis_container_id: 158

# Docker volumes backup configuration
backup_docker_volumes_enabled: true
backup_docker_containers:
  - container_id: 151
    name: keycloak
    volumes:
      - "/opt/keycloak"
  - container_id: 153
    name: gitlab
    volumes:
      - "/opt/gitlab/config"
      - "/opt/gitlab/data"
      - "/opt/gitlab/logs"
  - container_id: 155
    name: nextcloud
    volumes:
      - "/opt/nextcloud"
  - container_id: 163
    name: mattermost
    volumes:
      - "/opt/mattermost/config"
      - "/opt/mattermost/data"
      - "/opt/mattermost/logs"
  - container_id: 170
    name: webtop
    volumes:
      - "/opt/webtop"

# Proxmox configuration files backup
backup_proxmox_configs_enabled: true
backup_proxmox_configs:
  - "/etc/pve/lxc/*.conf"
  - "/etc/pve/nodes/*/qemu-server/*.conf"
  - "/etc/network/interfaces"
  - "/etc/traefik"
  - "/usr/local/lib/loopia-ddns"

# Verification
backup_verify_enabled: true
backup_verify_postgresql: true
backup_verify_container_backups: true

# Notifications
backup_notify_enabled: false
backup_notify_email: ""
backup_notify_on_success: false
backup_notify_on_failure: true
