---
- name: Check if LDAP group {{ ldap_group }} exists
  ansible.builtin.command:
    cmd: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b "cn={{ ldap_group }},{{ ldap_groups_base_dn }}" dn
  register: ldap_group_lookup
  changed_when: false
  failed_when: ldap_group_lookup.rc not in [0, 32]

- name: Render LDAP group LDIF for {{ ldap_group }}
  ansible.builtin.template:
    src: group.ldif.j2
    dest: "/tmp/ldap-group-{{ ldap_group }}.ldif"
    owner: root
    group: root
    mode: "0600"
  vars:
    ldap_group_name: "{{ ldap_group }}"
  when: ldap_group_lookup.rc == 32

- name: Create LDAP group {{ ldap_group }}
  ansible.builtin.command:
    cmd: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ldap-group-{{ ldap_group }}.ldif
  when: ldap_group_lookup.rc == 32

- name: Remove temporary LDAP group LDIF for {{ ldap_group }}
  ansible.builtin.file:
    path: "/tmp/ldap-group-{{ ldap_group }}.ldif"
    state: absent
  when: ldap_group_lookup.rc == 32
