---
gitlab_container_id: 153
gitlab_hostname: gitlab
gitlab_domain: viljo.se
gitlab_memory: 8192
gitlab_cores: 4
gitlab_disk: 128
gitlab_swap: 2048
gitlab_bridge: "{{ dmz_bridge | default('vmbr3') }}"
gitlab_ip_config: "172.16.10.153/24"
gitlab_vlan_tag: null
gitlab_gateway: "{{ dmz_gateway | default('172.16.10.101') }}"
gitlab_dns_servers: "{{ dmz_dns_servers | default(['1.1.1.1', '8.8.8.8']) }}"
gitlab_rootfs_storage: local-lvm
gitlab_unprivileged: false
gitlab_start_onboot: true
gitlab_features: {}
gitlab_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
gitlab_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"
gitlab_root_password: "{{ vault_gitlab_root_password | default('') }}"
gitlab_external_url: "https://gitlab.{{ gitlab_domain }}"
gitlab_db_adapter: postgresql
gitlab_db_encoding: unicode
gitlab_db_host: "172.16.10.150"
gitlab_db_port: 5432
gitlab_db_database: gitlab
gitlab_db_username: gitlab
gitlab_db_password: "{{ vault_postgres_gitlab_password | default('') }}"
gitlab_omnibus_package: gitlab-ce
gitlab_edition_repo: "deb https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/debian/ bookworm main"
gitlab_letsencrypt_enable: false
gitlab_letsencrypt_email: "admin@{{ gitlab_domain }}"
gitlab_registry_enable: true
gitlab_initial_root_password: "{{ vault_gitlab_root_password | default('') }}"
gitlab_rootfs_path: "/var/lib/lxc/{{ gitlab_container_id }}/rootfs"
gitlab_apt_retry_attempts: 5
gitlab_debian_suite: trixie
gitlab_debian_updates_suite: trixie-updates
gitlab_debian_security_suite: trixie-security
gitlab_debian_components:
  - main
  - contrib
  - non-free-firmware
gitlab_debian_mirror_uris:
  - http://deb.debian.org/debian
  - http://ftp.se.debian.org/debian
  - http://ftp.de.debian.org/debian
gitlab_debian_security_uris:
  - http://security.debian.org/debian-security
  - http://deb.debian.org/debian-security
gitlab_ldap_enable: true
gitlab_ldap_label: "Infra LDAP"
gitlab_ldap_host: "{{ ldap_service_host }}"
gitlab_ldap_port: "{{ ldap_service_port }}"
gitlab_ldap_uid: uid
gitlab_ldap_bind_dn: "{{ ldap_admin_bind_dn }}"
gitlab_ldap_bind_password: "{{ ldap_admin_password }}"
gitlab_ldap_base: "{{ ldap_suffix }}"
gitlab_ldap_group_base: "{{ ldap_groups_base_dn }}"
gitlab_ldap_encryption: plain
gitlab_ldap_verify_certificates: false
gitlab_ldap_active_directory: false
gitlab_ldap_allow_username_or_email_login: true
gitlab_ldap_lowercase_usernames: true
gitlab_ldap_user_filter: "(&(objectClass=inetOrgPerson))"
gitlab_ldap_attribute_username: uid
gitlab_ldap_attribute_email: mail
gitlab_ldap_attribute_name: cn
gitlab_ldap_attribute_first_name: givenName
gitlab_ldap_attribute_last_name: sn
