---
# Webtop Browser Workspace deployment via Proxmox API

# Container configuration
webtop_container_id: 170
webtop_hostname: "webtop"
webtop_template_file: "debian-13-standard_13.1-2_amd64.tar.zst"
webtop_external_domain: "viljo.se"

# Resources
webtop_cores: 4
webtop_memory: 4096
webtop_swap: 1024
webtop_disk: "40"
webtop_rootfs_storage: "local-lvm"

# Network
webtop_bridge: "vmbr3"
webtop_ip_address: "172.16.10.170"
webtop_netmask: "24"
webtop_gateway: "172.16.10.101"
webtop_dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"

# Container settings
webtop_unprivileged: false
webtop_features: "nesting=1"

# Webtop configuration
webtop_version: "latest"
webtop_data_dir: "/opt/webtop"
webtop_compose_file: "/opt/webtop/docker-compose.yml"
webtop_service_port: 3000
webtop_desktop_environment: "xfce"

# Passwords
webtop_root_password: "{{ vault_webtop_root_password }}"
webtop_user_password: "{{ vault_webtop_user_password }}"
