---
timezone: UTC
public_domain: example.com
loopia_api_user: "{{ vault_loopia_api_user | default('loopia-user@example.com') }}"
loopia_api_password: "{{ vault_loopia_api_password | default('replace-me') }}"
traefik_acme_email: "admin@{{ public_domain }}"
traefik_dns_challenge_provider: loopia
loopia_dns_records:
  - host: "@"
    ttl: 600
  - host: demo
  - host: gitlab
  - host: netbox
  - host: keycloak
  - host: nextcloud
  - host: jellyfin
  - host: homeassistant
  - host: cosmos
  - host: qbittorrent
  - host: wazuh
  - host: openmediavault
  - host: zipline
traefik_services:
  - name: demo
    host: "demo.{{ public_domain }}"
    container_id: "{{ demo_site_container_id }}"
    port: "{{ demo_site_service_port }}"
  - name: gitlab
    host: "gitlab.{{ public_domain }}"
    container_id: "{{ gitlab_container_id }}"
    port: 80
  - name: keycloak
    host: "keycloak.{{ public_domain }}"
    container_id: "{{ keycloak_container_id }}"
    port: 8080
  - name: netbox
    host: "netbox.{{ public_domain }}"
    container_id: "{{ netbox_container_id }}"
    port: 8001
  - name: nextcloud
    host: "nextcloud.{{ public_domain }}"
    container_id: "{{ nc_container_id }}"
    port: 80
  - name: jellyfin
    host: "jellyfin.{{ public_domain }}"
    container_id: "{{ jellyfin_container_id }}"
    port: 8096
  - name: homeassistant
    host: "homeassistant.{{ public_domain }}"
    container_id: "{{ ha_container_id }}"
    port: 8123
  - name: cosmos
    host: "cosmos.{{ public_domain }}"
    container_id: "{{ cosmos_container_id }}"
    port: 9000
  - name: qbittorrent
    host: "qbittorrent.{{ public_domain }}"
    container_id: "{{ qbittorrent_container_id }}"
    port: "{{ qbittorrent_web_port }}"
  - name: wazuh
    host: "wazuh.{{ public_domain }}"
    container_id: "{{ wazuh_container_id }}"
    port: 5601
    scheme: https
    insecure_skip_verify: true
  - name: openmediavault
    host: "openmediavault.{{ public_domain }}"
    container_id: "{{ omv_container_id }}"
    port: 443
    scheme: https
    insecure_skip_verify: true
  - name: zipline
    host: "zipline.{{ public_domain }}"
    container_id: "{{ zipline_container_id }}"
    port: 3000
management_bridge: vmbr0
public_bridge: vmbr1
