---
zabbix_container_id: 166
zabbix_hostname: zabbix
zabbix_bridge: "{{ public_bridge }}"
zabbix_ip_address: 172.16.10.166
zabbix_ip_config: "{{ zabbix_ip_address }}/{{ dmz_prefix }}"
zabbix_gateway: "{{ dmz_gateway }}"
zabbix_dns_servers:
  - 172.16.10.1
  - 1.1.1.1
zabbix_root_password: "{{ vault_zabbix_root_password }}"
