---
# Nextcloud File Storage deployment via Proxmox API

# Container configuration
nextcloud_container_id: 155
nextcloud_hostname: "nextcloud"
nextcloud_template_file: "debian-13-standard_13.1-2_amd64.tar.zst"
nextcloud_external_domain: "viljo.se"

# Resources
nextcloud_cores: 4
nextcloud_memory: 8192
nextcloud_swap: 2048
nextcloud_disk: "100"
nextcloud_rootfs_storage: "local-lvm"

# Network
nextcloud_bridge: "vmbr3"
nextcloud_ip_address: "172.16.10.155"
nextcloud_netmask: "24"
nextcloud_gateway: "172.16.10.101"
nextcloud_dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"

# Container settings
nextcloud_unprivileged: false
nextcloud_features: "nesting=1"

# Nextcloud configuration
nextcloud_version: "32.0.0"
nextcloud_data_dir: "/opt/nextcloud"
nextcloud_compose_file: "/opt/nextcloud/docker-compose.yml"
nextcloud_service_port: 80

# Database configuration
nextcloud_db_host: "172.16.10.150"
nextcloud_db_port: 5432
nextcloud_db_name: "nextcloud"
nextcloud_db_user: "nextcloud"
nextcloud_db_password: "{{ vault_postgres_nextcloud_password }}"

# Redis configuration
nextcloud_redis_host: "172.16.10.158"
nextcloud_redis_port: 6379
nextcloud_redis_password: "{{ vault_redis_password }}"

# Admin credentials
nextcloud_admin_user: "admin"
nextcloud_admin_password: "{{ vault_nextcloud_admin_password }}"

# Passwords
nextcloud_root_password: "{{ vault_nextcloud_root_password }}"
