---
# =============================================================================
# Portainer Container Management - Default Variables
# =============================================================================
# Configuration for Portainer deployment in LXC container with Docker support.
# Portainer provides a web-based UI for managing Docker containers, images,
# networks, and volumes across single or multiple Docker hosts.
#
# References:
#   - https://www.portainer.io/
#   - ADR: docs/adr/002-container-id-standardization.md
#   - Container Mapping: docs/architecture/container-mapping.md
# =============================================================================

# -----------------------------------------------------------------------------
# Container Identification
# -----------------------------------------------------------------------------
# Container ID standardized per ADR-002: .61 = Container management tool
portainer_container_id: 61
portainer_hostname: portainer
portainer_domain: infra.local

# -----------------------------------------------------------------------------
# Container Resources
# -----------------------------------------------------------------------------
# Moderate resources for Portainer web UI and agent
# Minimum: 512MB RAM, 1 core, 8GB disk
# Recommended: 1GB RAM, 2 cores, 16GB disk for better performance
portainer_memory: 1024
portainer_cores: 2
portainer_disk: 16
portainer_swap: 512

# -----------------------------------------------------------------------------
# Container Network Configuration
# -----------------------------------------------------------------------------
portainer_bridge: "{{ public_bridge | default('vmbr3') }}"
portainer_ip_address: 172.16.10.61
portainer_netmask: 24
portainer_ip_config: "{{ portainer_ip_address }}/{{ portainer_netmask }}"
portainer_vlan_tag: null
portainer_gateway: 172.16.10.1
portainer_dns_servers:
  - 172.16.10.1
  - 1.1.1.1

# -----------------------------------------------------------------------------
# Container Storage and Template
# -----------------------------------------------------------------------------
portainer_rootfs_storage: local-lvm

# Using Debian 13 (Trixie) standard template
portainer_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
portainer_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"

# -----------------------------------------------------------------------------
# Container Security and Features
# -----------------------------------------------------------------------------
# Unprivileged container with nesting for Docker support
portainer_unprivileged: true
portainer_start_onboot: true
portainer_features:
  nesting: 1

# -----------------------------------------------------------------------------
# Container Access
# -----------------------------------------------------------------------------
portainer_root_password: "{{ vault_portainer_root_password | default('') }}"
portainer_rootfs_path: "/var/lib/lxc/{{ portainer_container_id }}/rootfs"

# -----------------------------------------------------------------------------
# Portainer Application Configuration
# -----------------------------------------------------------------------------
# Service ports
portainer_service_port_http: 9000  # HTTP web UI
portainer_service_port_https: 9443 # HTTPS web UI
portainer_service_port_edge: 8000  # Edge agent tunnel port (optional)

# Public hostname for Traefik routing
portainer_public_hostname: "portainer.viljo.se"

# Portainer edition
# Options: "portainer-ce" (Community Edition) or "portainer-ee" (Business Edition)
portainer_edition: "portainer-ce"

# Portainer image version
# Use "latest" for most recent stable, or specify version like "2.19.4"
portainer_version: "latest"

# -----------------------------------------------------------------------------
# Data Persistence
# -----------------------------------------------------------------------------
# Docker Compose deployment path
portainer_compose_path: /opt/portainer

# Portainer data volume name (managed by Docker)
portainer_data_volume: portainer_data

# -----------------------------------------------------------------------------
# Agent Configuration (Optional)
# -----------------------------------------------------------------------------
# Set to true to also deploy Portainer Agent for remote Docker management
# Agent allows Portainer to manage other Docker hosts
portainer_deploy_agent: false
portainer_agent_port: 9001
