---
# SSH Bastion (Jump Host) deployment via Proxmox API

# Container configuration
bastion_container_id: 110
bastion_hostname: "ssh"
bastion_template_file: "debian-13-standard_13.1-2_amd64.tar.zst"
bastion_external_domain: "viljo.se"

# Resources
bastion_cores: 1
bastion_memory: 512
bastion_swap: 256
bastion_disk: "8"
bastion_rootfs_storage: "local-lvm"

# Network - Management network, NOT DMZ
bastion_bridge: "vmbr0"
bastion_ip_address: "192.168.1.110"
bastion_netmask: "16"
bastion_gateway: "192.168.1.1"
bastion_dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"

# Container settings
bastion_unprivileged: true
bastion_features: "nesting=0"

# SSH Configuration
bastion_ssh_port: 22
bastion_permit_root_login: "prohibit-password"
bastion_password_authentication: false
bastion_pubkey_authentication: true
bastion_max_auth_tries: 3
bastion_max_sessions: 10
bastion_client_alive_interval: 300
bastion_client_alive_count_max: 2

# Fail2ban settings
bastion_fail2ban_enabled: true
bastion_fail2ban_maxretry: 3
bastion_fail2ban_bantime: 3600
bastion_fail2ban_findtime: 600

# Passwords (from vault)
bastion_root_password: "{{ vault_bastion_root_password }}"

# Authorized SSH keys for bastion access
bastion_authorized_keys: "{{ proxmox_root_authorized_keys }}"
