---
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  delegate_to: bastion_container

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  delegate_to: bastion_container
