---
# Container configuration
wireguard_container_id: 90
wireguard_hostname: wireguard
wireguard_domain: infra.local
wireguard_memory: 1024
wireguard_cores: 1
wireguard_disk: 8
wireguard_swap: 512

# Network configuration - deployed on management network (vmbr0) with static IP
wireguard_bridge: "{{ management_bridge | default('vmbr0') }}"
wireguard_ip_config: "192.168.1.90/24"
wireguard_gateway: "192.168.1.1"
wireguard_vlan_tag: null
wireguard_dns_servers:
  - 192.168.1.1
  - 1.1.1.1

# Container options
wireguard_rootfs_storage: local-lvm
wireguard_unprivileged: true
wireguard_start_onboot: true
wireguard_features:
  nesting: 1

# Template configuration
wireguard_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
wireguard_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"

# Security
wireguard_root_password: "{{ vault_wireguard_root_password | default('') }}"

# WireGuard VPN configuration
wireguard_config_dir: /etc/wireguard
wireguard_interface: wg0
wireguard_listen_port: 51820
wireguard_tunnel_address: "192.168.100.1/24"  # VPN tunnel network (192.168.100.0/24)
wireguard_private_key: "{{ vault_wireguard_private_key | default('') }}"

# Peer configurations (empty by default - configure in inventory)
# Example peer configuration:
# wireguard_peer_configs:
#   - name: "John's Laptop"
#     public_key: "AbCdEf1234567890abcdef1234567890abcdef12="
#     allowed_ips: "192.168.100.10/32"
#     persistent_keepalive: 25
#   - name: "Jane's Phone"
#     public_key: "XyZ9876543210XyZ9876543210XyZ9876543210="
#     allowed_ips: "192.168.100.11/32"
#     persistent_keepalive: 25
wireguard_peer_configs: []

# Internal paths
wireguard_rootfs_path: "/var/lib/lxc/{{ wireguard_container_id }}/rootfs"
