---
# Loopia DDNS - runs on Proxmox host

- name: Create Loopia DDNS directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /usr/local/lib/loopia-ddns
    - /var/lib/loopia-ddns

- name: Create Loopia DDNS update script
  ansible.builtin.template:
    src: update.py.j2
    dest: /usr/local/lib/loopia-ddns/update.py
    owner: root
    group: root
    mode: '0755'

- name: Create Loopia DDNS wrapper script
  ansible.builtin.template:
    src: loopia-ddns.j2
    dest: /usr/local/bin/loopia-ddns
    owner: root
    group: root
    mode: '0755'

- name: Create Loopia DDNS systemd service
  ansible.builtin.template:
    src: loopia-ddns.service.j2
    dest: /etc/systemd/system/loopia-ddns.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Create Loopia DDNS systemd timer
  ansible.builtin.template:
    src: loopia-ddns.timer.j2
    dest: /etc/systemd/system/loopia-ddns.timer
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart loopia-ddns timer

- name: Enable and start Loopia DDNS timer
  ansible.builtin.systemd:
    name: loopia-ddns.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Run initial DNS update
  ansible.builtin.command:
    cmd: /usr/local/bin/loopia-ddns
  changed_when: true
