---
- name: Ensure Wazuh template cache directory exists
  ansible.builtin.file:
    path: "{{ wazuh_template_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download template for Wazuh container
  ansible.builtin.get_url:
    url: "{{ wazuh_template_url }}"
    dest: "{{ wazuh_template_file }}"
    mode: "0644"
    force: false
  when: not ansible_check_mode

- name: Compose Wazuh container network configuration
  ansible.builtin.set_fact:
    wazuh_net0: >-
      name=eth0,bridge={{ wazuh_bridge }}{% if wazuh_vlan_tag %},tag={{ wazuh_vlan_tag }}{% endif %},ip={{ wazuh_ip_config }}{% if wazuh_gateway is defined and wazuh_gateway %},gw={{ wazuh_gateway }}{% endif %}

- name: Ensure Wazuh container exists
  ansible.builtin.shell: |
    pct create {{ wazuh_container_id }} {{ wazuh_template_file }} \
      --hostname {{ wazuh_hostname }} \
      --cores {{ wazuh_cores }} \
      --memory {{ wazuh_memory }} \
      --swap {{ wazuh_swap }} \
      --rootfs {{ wazuh_rootfs_storage }}:{{ wazuh_disk }} \
      --net0 {{ wazuh_net0 }} \
      {% if wazuh_unprivileged %}--unprivileged 1{% endif %}
  args:
    creates: "/etc/pve/lxc/{{ wazuh_container_id }}.conf"
  when: not ansible_check_mode

- name: Stat Wazuh container configuration
  ansible.builtin.stat:
    path: "/etc/pve/lxc/{{ wazuh_container_id }}.conf"
  register: wazuh_container_conf

- name: Ensure Wazuh container onboot flag is set
  ansible.builtin.lineinfile:
    path: "/etc/pve/lxc/{{ wazuh_container_id }}.conf"
    regexp: '^onboot:'
    line: "onboot: {{ 1 if wazuh_start_onboot else 0 }}"
    insertafter: EOF
  when: wazuh_container_conf.stat.exists

- name: Read Wazuh container status
  ansible.builtin.command:
    cmd: pct status {{ wazuh_container_id }}
  register: wazuh_status
  changed_when: false
  failed_when: wazuh_status.rc not in [0, 2]
  when: wazuh_container_conf.stat.exists

- name: Start Wazuh container
  ansible.builtin.command:
    cmd: pct start {{ wazuh_container_id }}
  when:
    - not ansible_check_mode
    - wazuh_container_conf.stat.exists
    - wazuh_status.rc is defined
    - (wazuh_status.rc != 0 or ('stopped' in wazuh_status.stdout | default('')))

- name: Wait for Wazuh container to boot
  ansible.builtin.command:
    cmd: pct exec {{ wazuh_container_id }} -- bash -lc "true"
  register: wazuh_boot_probe
  failed_when: false
  changed_when: false
  retries: 10
  delay: 5
  until: wazuh_boot_probe.rc == 0
  when:
    - not ansible_check_mode
    - wazuh_container_conf.stat.exists

- name: Ensure Wazuh root password is set
  ansible.builtin.command:
    cmd: >
      pct exec {{ wazuh_container_id }} -- bash -lc "echo 'root:{{ wazuh_root_password }}' | chpasswd"
  no_log: true
  when:
    - not ansible_check_mode
    - wazuh_container_conf.stat.exists
    - wazuh_root_password is defined
    - wazuh_root_password | length > 0

- name: Check Wazuh provisioning marker
  ansible.builtin.command:
    cmd: >
      pct exec {{ wazuh_container_id }} -- bash -lc "test -f /etc/wazuh/.provisioned"
  register: wazuh_provision_marker
  changed_when: false
  failed_when: false
  when: wazuh_container_conf.stat.exists

- name: Install Docker for Wazuh stack
  ansible.builtin.command:
    cmd: >
      pct exec {{ wazuh_container_id }} -- bash -lc "apt-get update && apt-get install -y docker.io docker-compose-plugin"
  when:
    - not ansible_check_mode
    - wazuh_container_conf.stat.exists
    - wazuh_provision_marker.rc is defined
    - wazuh_provision_marker.rc != 0

- name: Ensure Wazuh compose directory exists on host
  ansible.builtin.file:
    path: "{{ wazuh_rootfs_path }}{{ wazuh_compose_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Wazuh docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wazuh_rootfs_path }}{{ wazuh_compose_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  notify: restart wazuh stack

- name: Touch Wazuh provisioning marker
  ansible.builtin.command:
    cmd: >
      pct exec {{ wazuh_container_id }} -- bash -lc "mkdir -p /etc/wazuh && touch /etc/wazuh/.provisioned"
  when:
    - not ansible_check_mode
    - wazuh_container_conf.stat.exists
    - wazuh_provision_marker.rc is defined
    - wazuh_provision_marker.rc != 0
