# SSH Configuration Contract
# Feature: External SSH Access via viljo.se
# Purpose: Define expected SSH daemon configuration for external access

---
# Contract Version
version: "1.0.0"
contract_type: "infrastructure_configuration"
applies_to: "Proxmox host SSH daemon"

# Configuration Requirements
ssh_daemon:
  service_name: "sshd"
  config_file: "/etc/ssh/sshd_config"

  # Security Requirements (MUST)
  required_settings:
    # Authentication
    - name: "PermitRootLogin"
      value: "without-password"  # Keys only, no password
      rationale: "SR-001: Key-based authentication required"

    - name: "PasswordAuthentication"
      value: "no"
      rationale: "SR-001: Disable password auth for external access"

    - name: "PubkeyAuthentication"
      value: "yes"
      rationale: "FR-004: Support key-based authentication"

    - name: "PermitEmptyPasswords"
      value: "no"
      rationale: "Security hardening"

    # Protocol Version
    - name: "Protocol"
      value: "2"
      rationale: "Security hardening - SSH v1 has known vulnerabilities"

    # Session Management
    - name: "ClientAliveInterval"
      value: "300"  # 5 minutes
      rationale: "Prevent hung sessions, reasonable timeout"

    - name: "ClientAliveCountMax"
      value: "3"
      rationale: "Allow 3 missed keepalives (15 min total)"

    - name: "MaxAuthTries"
      value: "3"
      rationale: "Limit brute force attempts before disconnect"

    - name: "LoginGraceTime"
      value: "60"  # 1 minute
      rationale: "Limit time for authentication"

    # Logging
    - name: "LogLevel"
      value: "VERBOSE"
      rationale: "FR-007, SR-004: Detailed audit logging"

    - name: "SyslogFacility"
      value: "AUTH"
      rationale: "Route logs to auth facility for fail2ban"

    # Disabled Features
    - name: "X11Forwarding"
      value: "no"
      rationale: "Not needed for server management, reduce attack surface"

    - name: "PrintMotd"
      value: "no"
      rationale: "Reduce login verbosity"

    - name: "PermitUserEnvironment"
      value: "no"
      rationale: "Security hardening"

  # Recommended Strong Cryptography (SHOULD)
  recommended_settings:
    - name: "Ciphers"
      value: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
      rationale: "Use strong, modern ciphers only"

    - name: "MACs"
      value: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
      rationale: "Use strong MAC algorithms"

    - name: "KexAlgorithms"
      value: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
      rationale: "Use strong key exchange algorithms"

  # Optional Settings (MAY)
  optional_settings:
    - name: "Port"
      default_value: "22"
      configurable: true
      rationale: "Internal port is 22, external port may differ via port forwarding"

    - name: "AllowUsers"
      default_value: "root"
      configurable: true
      rationale: "Restrict SSH access to specific users"

    - name: "MaxSessions"
      default_value: "10"
      configurable: true
      rationale: "Limit concurrent sessions per connection"

# Fail2ban Integration Contract
fail2ban:
  jail_name: "sshd"
  config_file: "/etc/fail2ban/jail.d/sshd.conf"

  required_settings:
    - name: "enabled"
      value: true
      rationale: "SR-003: Brute force protection required"

    - name: "port"
      value: "22"  # Internal port
      rationale: "Monitor SSH port"

    - name: "filter"
      value: "sshd"
      rationale: "Use built-in SSH filter"

    - name: "logpath"
      value: "%(sshd_log)s"  # /var/log/auth.log on Debian
      rationale: "Monitor SSH authentication logs"

    - name: "backend"
      value: "systemd"
      rationale: "Use systemd journal for log monitoring"

    - name: "maxretry"
      value: 5
      rationale: "Ban after 5 failed attempts"

    - name: "findtime"
      value: 600  # 10 minutes
      rationale: "Count failures within 10-minute window"

    - name: "bantime"
      value: 3600  # 1 hour
      rationale: "Ban for 1 hour on threshold breach"

    - name: "ignoreip"
      value: ["127.0.0.1/8", "192.168.0.0/16"]
      rationale: "Whitelist localhost and internal network"

# DNS Configuration Contract
dns:
  provider: "Loopia"
  record_type: "A"

  required_settings:
    - name: "domain"
      value: "viljo.se"
      rationale: "FR-002: External domain name"

    - name: "ttl"
      value: 300  # 5 minutes
      rationale: "SC-007: Enable fast IP change propagation"

    - name: "update_interval"
      value: 300  # 5 minutes
      rationale: "Check for IP changes every 5 minutes"

  expectations:
    - "DNS A record resolves to current external IP"
    - "DNS resolution completes in under 2 seconds (SC-002)"
    - "IP changes reflected in DNS within 5 minutes (SC-007)"

# Port Forwarding Contract
port_forwarding:
  device_type: "Router/Firewall"
  protocol: "TCP"

  required_configuration:
    - name: "external_port"
      value: "configurable"  # Recommend 2222 or non-standard
      rationale: "Reduce automated scan exposure"

    - name: "internal_ip"
      value: "192.168.1.3"
      rationale: "Proxmox host IP address"

    - name: "internal_port"
      value: 22
      rationale: "SSH daemon port on Proxmox"

    - name: "enabled"
      value: true
      rationale: "Rule must be active"

    - name: "persistent"
      value: true
      rationale: "FR-006: Survive router reboots"

  expectations:
    - "External connections to viljo.se:{external_port} reach 192.168.1.3:22"
    - "Port forwarding persists through 100% of reboots (SC-005)"
    - "Connection establishment under 10 seconds (SC-003)"

# SSH Key Management Contract
ssh_keys:
  key_type: "ed25519"  # Preferred
  alternative_types: ["rsa-4096"]  # Accepted for compatibility

  required_configuration:
    - name: "authorized_keys_file"
      value: "/root/.ssh/authorized_keys"
      rationale: "Standard SSH key location"

    - name: "file_permissions"
      value: "0600"
      rationale: "Security requirement for authorized_keys"

    - name: "directory_permissions"
      value: "0700"
      rationale: "Security requirement for .ssh directory"

    - name: "minimum_keys"
      value: 1
      rationale: "At least one admin key must exist"

  storage:
    - "Public keys in authorized_keys file"
    - "Private keys stored securely by administrators (not in repo)"
    - "Deployment keys encrypted in Ansible Vault"

  expectations:
    - "Key-based authentication succeeds for authorized administrators"
    - "Password authentication fails (disabled)"
    - "Keys rotated annually (documented in runbook)"

# Audit Logging Contract
audit_logging:
  log_facility: "AUTH"
  log_level: "VERBOSE"

  required_logs:
    - event: "SSH connection attempt"
      fields: ["timestamp", "source_ip", "username", "auth_method"]
      rationale: "SC-004: 100% audit coverage"

    - event: "SSH authentication success"
      fields: ["timestamp", "source_ip", "username", "session_id"]
      rationale: "Track successful access"

    - event: "SSH authentication failure"
      fields: ["timestamp", "source_ip", "username", "failure_reason"]
      rationale: "Detect brute force attacks"

    - event: "SSH session disconnect"
      fields: ["timestamp", "session_id", "duration"]
      rationale: "Track session lifecycle"

    - event: "fail2ban IP ban"
      fields: ["timestamp", "banned_ip", "reason", "ban_duration"]
      rationale: "Track security actions"

  retention:
    - "Local logs: 90 days minimum"
    - "Wazuh SIEM: 1 year (if available)"

  expectations:
    - "All connection attempts logged (SC-004)"
    - "Logs searchable and parseable"
    - "Alerts generated for repeated failures"

# Success Criteria Mapping
success_criteria:
  SC-001:
    description: "Administrator can successfully connect via ssh root@viljo.se"
    validation: "Manual test from external network"

  SC-002:
    description: "DNS resolution for viljo.se completes in under 2 seconds"
    validation: "dig viljo.se | grep 'Query time'"

  SC-003:
    description: "SSH connection establishment under 10 seconds"
    validation: "time ssh -o ConnectTimeout=10 root@viljo.se"

  SC-004:
    description: "100% of connection attempts logged"
    validation: "grep 'sshd' /var/log/auth.log | wc -l"

  SC-005:
    description: "Port forwarding persists through reboots"
    validation: "Reboot router, verify ssh connection still works"

  SC-006:
    description: "Zero unauthorized access incidents"
    validation: "Review fail2ban logs, Wazuh alerts"

  SC-007:
    description: "External IP changes reflected in DNS within 5 minutes"
    validation: "Simulate IP change, monitor loopia_ddns logs"

# Testing Contract
testing:
  pre_deployment:
    - "ansible-lint playbooks/external-ssh-access.yml"
    - "yamllint roles/proxmox/templates/"
    - "sshd -t (syntax check on test host)"

  post_deployment:
    - "SSH connection from external network"
    - "Verify fail2ban is active: fail2ban-client status sshd"
    - "Verify DNS resolution: dig viljo.se"
    - "Check auth logs: tail -f /var/log/auth.log"
    - "Attempt password auth (should fail)"
    - "Trigger fail2ban ban (5 failures), verify IP banned"

  rollback_validation:
    - "Backup sshd_config restored"
    - "SSH access still functional"
    - "fail2ban uninstalled/disabled cleanly"

# Compliance Requirements
compliance:
  constitutional:
    - principle: "Infrastructure as Code"
      status: "COMPLIANT"
      evidence: "All configs managed via Ansible roles"

    - principle: "Security-First Design"
      status: "COMPLIANT"
      evidence: "Key-based auth, fail2ban, audit logging"

    - principle: "Idempotent Operations"
      status: "COMPLIANT"
      evidence: "Ansible ensures idempotency, sshd -t validates before restart"

    - principle: "Automated Operations"
      status: "PARTIAL"
      evidence: "SSH/DNS automated, router port forwarding may be manual"
      exceptions: "Router automation depends on hardware capability"
