---
# Container Configuration
wazuh_container_id: 62
wazuh_hostname: wazuh
wazuh_domain: "{{ public_domain | default('viljo.se') }}"
wazuh_fqdn: "{{ wazuh_hostname }}.{{ wazuh_domain }}"
wazuh_memory: 8192
wazuh_cores: 4
wazuh_disk: 64
wazuh_swap: 2048

# Network Configuration
wazuh_bridge: "{{ dmz_bridge | default('vmbr3') }}"
wazuh_ip_address: "172.16.10.{{ wazuh_container_id }}"
wazuh_ip_config: "{{ wazuh_ip_address }}/24"
wazuh_gateway: "{{ dmz_gateway | default('172.16.10.1') }}"
wazuh_dns_servers: ["172.16.10.1", "1.1.1.1"]
wazuh_vlan_tag: null

# Storage Configuration
wazuh_rootfs_storage: local-lvm
wazuh_rootfs_path: "/var/lib/lxc/{{ wazuh_container_id }}/rootfs"

# Container Features
wazuh_unprivileged: true
wazuh_start_onboot: true
wazuh_features:
  nesting: 1

# Template Configuration
wazuh_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
wazuh_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"

# Security
wazuh_root_password: "{{ vault_wazuh_root_password | default('') }}"

# Wazuh Configuration
wazuh_compose_path: /opt/wazuh
wazuh_version: 4.9.2
wazuh_api_user: wazuh
wazuh_api_password: "{{ vault_wazuh_api_password | default('wazuh') }}"
wazuh_indexer_password: "{{ vault_wazuh_indexer_password | default('SecretPassword') }}"

# Traefik Integration
wazuh_enable_traefik: true
wazuh_traefik_router: wazuh
wazuh_traefik_entrypoint: websecure
