---
# Complete Infrastructure Backup Playbook
# Backs up all containers, databases, Docker volumes, and configurations

- name: Backup Infrastructure
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  pre_tasks:
    - name: Check required variables
      ansible.builtin.assert:
        that:
          - vault_postgres_user_password is defined
        fail_msg: "Required vault variables not defined. Ensure vault is decrypted."

    - name: Ensure backup dependencies are installed
      ansible.builtin.apt:
        name:
          - postgresql-client
          - rsync
        state: present
        update_cache: yes

  roles:
    - role: backup_infrastructure

  post_tasks:
    - name: Display backup location
      ansible.builtin.debug:
        msg:
          - ""
          - "Backup completed successfully!"
          - "Location: {{ backup_base_dir }}/{{ backup_timestamp }}"
          - ""
          - "To restore, see: {{ backup_base_dir }}/{{ backup_timestamp }}/BACKUP_SUMMARY.txt"
