---
- name: Rebuild DMZ services behind the firewall
  hosts: proxmox_admin
  become: true
  roles:
    - proxmox
    - role: network
      tags: ["network"]
    - role: firewall
      tags: ["firewall"]
    - role: loopia_dns
      tags: ["loopia_dns", "dns"]
    - role: loopia_ddns
      tags: ["loopia_ddns"]
    - role: dmz_cleanup
      tags: ["dmz_cleanup"]
    - postgresql
    - netbox
    - role: demo_site
      tags: ["demo_site"]
    - role: traefik
      tags: ["traefik"]
    - ldap
    - keycloak
    - jellyfin
    - homeassistant
    - openmediavault
    - role: nextcloud
      tags: ["nextcloud"]
    - role: gitlab
      tags: ["gitlab"]
    - gitlab_runner
    - zipline
    - qbittorrent
    - wazuh
    - wireguard
    - cosmos
