---
# Full Infrastructure Deployment
# Deploy all services in dependency order for disaster recovery

- name: Deploy Core Infrastructure Services
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  tasks:
    - name: Display deployment banner
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - " FULL INFRASTRUCTURE DEPLOYMENT"
          - "=========================================="
          - ""
          - "This playbook deploys all 11 services:"
          - "  1. PostgreSQL (150) - Database backend"
          - "  2. Redis (158) - Cache and message queue"
          - "  3. Bastion (110) - SSH jump host"
          - "  4. Keycloak (151) - SSO/Identity"
          - "  5. GitLab (153) - DevOps platform"
          - "  6. GitLab Runner (154) - CI/CD runners"
          - "  7. Nextcloud (155) - File storage"
          - "  8. Mattermost (163) - Team chat"
          - "  9. Webtop (170) - Browser workspace"
          - " 10. Demo Site (160) - Demo portal"
          - " 11. Firewall (101) - Already deployed"
          - ""
          - "Estimated total time: 30-45 minutes"
          - "=========================================="

# Phase 1: Backend Services (PostgreSQL, Redis)
- name: Phase 1 - Deploy Backend Services
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  roles:
    - role: postgresql_api
    - role: redis_api

# Phase 2: Infrastructure Services (Bastion, Keycloak)
- name: Phase 2 - Deploy Infrastructure Services
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  roles:
    - role: bastion_api
    - role: keycloak_api

# Phase 3: DevOps Services (GitLab, GitLab Runner)
- name: Phase 3 - Deploy DevOps Services
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  roles:
    - role: gitlab_api
    - role: gitlab_runner_api

# Phase 4: Collaboration Services (Nextcloud, Mattermost)
- name: Phase 4 - Deploy Collaboration Services
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  roles:
    - role: nextcloud_complete
    - role: mattermost_api

# Phase 5: Utility Services (Webtop, Demo Site)
- name: Phase 5 - Deploy Utility Services
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  roles:
    - role: webtop_api
    - role: demo_site

# Final Summary
- name: Deployment Complete
  hosts: proxmox_admin
  gather_facts: no
  become: no

  tasks:
    - name: Display completion summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - " DEPLOYMENT COMPLETE"
          - "=========================================="
          - ""
          - "All services deployed successfully!"
          - ""
          - "Next steps:"
          - "  1. Verify external access to all services"
          - "  2. Configure Traefik routing if needed"
          - "  3. Set up Keycloak SSO integrations"
          - "  4. Register GitLab Runner with GitLab"
          - "  5. Configure Nextcloud external storage"
          - ""
          - "Services access:"
          - "  - PostgreSQL: 172.16.10.150:5432"
          - "  - Redis: 172.16.10.158:6379"
          - "  - Bastion: ssh.viljo.se (192.168.1.110)"
          - "  - Keycloak: https://keycloak.viljo.se"
          - "  - GitLab: https://gitlab.viljo.se"
          - "  - Nextcloud: https://nextcloud.viljo.se"
          - "  - Mattermost: https://mattermost.viljo.se"
          - "  - Webtop: https://browser.viljo.se"
          - "  - Demo Site: https://demosite.viljo.se"
          - ""
          - "=========================================="
