---
- name: Deploy GitLab CE DevOps Platform
  hosts: proxmox_admin
  gather_facts: yes
  become: no

  tasks:
    - name: Load gitlab variables
      ansible.builtin.include_vars:
        file: ../roles/gitlab_api/defaults/main.yml

    - name: Apply gitlab_api role
      ansible.builtin.include_role:
        name: gitlab_api
        public: yes

    ##############################
    # SERVICE VERIFICATION       #
    ##############################

    - name: "VERIFY: Test GitLab HTTP endpoint (from Proxmox host)"
      ansible.builtin.uri:
        url: "http://{{ gitlab_ip_address }}/"
        method: GET
        status_code: [200, 302]
        timeout: 10
      register: gitlab_http
      failed_when: false


    - name: "VERIFY: Test GitLab HTTPS (external)"
      ansible.builtin.uri:
        url: "{{ gitlab_external_url }}"
        method: GET
        status_code: [200, 302]
        validate_certs: yes
        timeout: 30
      delegate_to: localhost
      register: gitlab_https
      failed_when: false

    - name: "VERIFY: Display verification results"
      ansible.builtin.debug:
        msg:
          - "=== GitLab Verification Results ==="
          - "HTTP Internal ({{gitlab_ip_address}}): {{ 'PASS ✅' if gitlab_http.status in [200, 302] else 'FAIL ❌ (HTTP ' + (gitlab_http.status|string) + ')' }}"
          - "HTTPS External ({{gitlab_external_url}}): {{ 'PASS ✅' if gitlab_https.status in [200, 302] else 'FAIL ❌ (' + (gitlab_https.msg|default('Error')|string) + ')' }}"

    - name: "VERIFY: Fail if critical checks failed"
      ansible.builtin.fail:
        msg:
          - "❌ GitLab verification FAILED"
          - "  HTTP Internal: {{ gitlab_http.status | default('ERROR') }}"
          - "  HTTPS External: {{ gitlab_https.status | default('ERROR') }}"
          - ""
          - "Troubleshooting:"
          - "  1. Check GitLab logs: ssh root@{{ ansible_host }} 'pct exec {{ gitlab_container_id }} -- docker logs gitlab'"
          - "  2. Check Docker status: ssh root@{{ ansible_host }} 'pct exec {{ gitlab_container_id }} -- docker ps -a'"
          - "  3. Check GitLab response: curl -I http://{{ gitlab_ip_address }}/"
          - "  4. Check Traefik routing for {{ gitlab_external_url }}"
          - "  5. Note: GitLab startup takes 5-10 minutes - container may be initializing"
      when: >
        gitlab_http.status is not defined or
        gitlab_http.status not in [200, 302] or
        gitlab_https.status is not defined or
        gitlab_https.status not in [200, 302]

    - name: "VERIFY: Display success message"
      ansible.builtin.debug:
        msg:
          - "✅ GitLab deployed and verified successfully"
          - "  Container ID: {{ gitlab_container_id }}"
          - "  IP: {{ gitlab_ip_address }}"
          - "  External URL: {{ gitlab_external_url }}"
          - "  Status: FUNCTIONAL ✅"
