---
- name: Deploy Mattermost Team Collaboration Platform
  hosts: proxmox_admin
  gather_facts: false
  become: false

  tasks:
    - name: Load mattermost variables
      ansible.builtin.include_vars:
        file: ../roles/mattermost_api/defaults/main.yml

    - name: Apply mattermost_api role
      ansible.builtin.include_role:
        name: mattermost_api
        public: yes

    ##############################
    # SERVICE VERIFICATION       #
    ##############################

    - name: "VERIFY: Test Mattermost HTTP endpoint (from Proxmox host)"
      ansible.builtin.uri:
        url: "http://{{ mattermost_ip_address }}:{{ mattermost_service_port }}/"
        method: GET
        status_code: [200]
        timeout: 10
      register: mattermost_http
      failed_when: false

    - name: "VERIFY: Test Mattermost HTTPS (external)"
      ansible.builtin.uri:
        url: "https://{{ mattermost_hostname }}.{{ mattermost_external_domain }}/"
        method: GET
        status_code: [200]
        validate_certs: yes
        timeout: 30
      delegate_to: localhost
      register: mattermost_https
      failed_when: false

    - name: "VERIFY: Display verification results"
      ansible.builtin.debug:
        msg:
          - "=== Mattermost Verification Results ==="
          - "HTTP Internal ({{mattermost_ip_address}}:{{mattermost_service_port}}): {{ 'PASS ✅' if mattermost_http.status == 200 else 'FAIL ❌ (HTTP ' + (mattermost_http.status|string) + ')' }}"
          - "HTTPS External ({{mattermost_hostname}}.{{mattermost_external_domain}}): {{ 'PASS ✅' if mattermost_https.status == 200 else 'FAIL ❌ (' + (mattermost_https.msg|default('Error')|string) + ')' }}"

    - name: "VERIFY: Fail if critical checks failed"
      ansible.builtin.fail:
        msg:
          - "❌ Mattermost verification FAILED"
          - "  HTTP Internal: {{ mattermost_http.status | default('ERROR') }}"
          - "  HTTPS External: {{ mattermost_https.status | default('ERROR') }}"
          - ""
          - "Troubleshooting:"
          - "  1. Check Mattermost logs: ssh root@{{ ansible_host }} 'pct exec {{ mattermost_container_id }} -- docker logs mattermost'"
          - "  2. Check Docker status: ssh root@{{ ansible_host }} 'pct exec {{ mattermost_container_id }} -- docker ps -a'"
          - "  3. Check container connectivity: curl http://{{ mattermost_ip_address }}:{{ mattermost_service_port }}/"
          - "  4. Check Traefik routing for {{ mattermost_hostname }}.{{ mattermost_external_domain }}"
      when: >
        mattermost_http.status is not defined or
        mattermost_http.status != 200 or
        mattermost_https.status is not defined or
        mattermost_https.status != 200

    - name: "VERIFY: Display success message"
      ansible.builtin.debug:
        msg:
          - "✅ Mattermost deployed and verified successfully"
          - "  Container ID: {{ mattermost_container_id }}"
          - "  IP: {{ mattermost_ip_address }}"
          - "  External URL: https://{{ mattermost_hostname }}.{{ mattermost_external_domain }}/"
          - "  Status: FUNCTIONAL ✅"
