---
- name: Configure Proxmox infrastructure node
  hosts: proxmox_admin
  become: true
  roles:
    - role: proxmox
      tags: ["proxmox"]
    - role: network
      tags: ["network"]
    - role: firewall
      tags: ["firewall"]
    - role: loopia_dns
      tags: ["loopia_dns", "dns"]
    - role: loopia_ddns
      tags: ["loopia_ddns"]
    - postgresql
    - netbox
    - coolify
    - role: zabbix
      tags: ["zabbix", "monitoring"]
    - role: demo_site
      tags: ["demo_site"]
    - role: traefik
      tags: ["traefik"]
    - ldap
    - keycloak
    - jellyfin
    - homeassistant
    - openmediavault
    - role: nextcloud
      tags: ["nextcloud"]
    - role: gitlab
      tags: ["gitlab"]
    - gitlab_runner
    - zipline
    - qbittorrent
    - portainer
    - wazuh
    - wireguard
