---
# PostgreSQL Database Server deployment via Proxmox API

# Container configuration
postgresql_container_id: 150
postgresql_hostname: "postgresql"
postgresql_template_file: "debian-13-standard_13.1-2_amd64.tar.zst"

# Resources
postgresql_cores: 4
postgresql_memory: 8192
postgresql_swap: 2048
postgresql_disk: "40"
postgresql_rootfs_storage: "local-lvm"

# Network
postgresql_bridge: "vmbr3"
postgresql_ip_address: "172.16.10.150"
postgresql_netmask: "24"
postgresql_gateway: "172.16.10.101"
postgresql_dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"

# Container settings
postgresql_unprivileged: false
postgresql_features: "nesting=0"

# PostgreSQL version
postgresql_version: "17"
postgresql_port: 5432

# PostgreSQL configuration
postgresql_max_connections: 200
postgresql_shared_buffers: "2GB"
postgresql_effective_cache_size: "6GB"
postgresql_maintenance_work_mem: "512MB"
postgresql_checkpoint_completion_target: 0.9
postgresql_wal_buffers: "16MB"
postgresql_default_statistics_target: 100
postgresql_random_page_cost: 1.1
postgresql_effective_io_concurrency: 200
postgresql_work_mem: "10485kB"
postgresql_min_wal_size: "1GB"
postgresql_max_wal_size: "4GB"

# Authentication
postgresql_listen_addresses: "*"
postgresql_authentication_timeout: "60s"

# Allowed networks for pg_hba.conf
postgresql_allowed_networks:
  - "172.16.10.0/24"  # DMZ network
  - "192.168.1.0/16"  # Management network

# Passwords (from vault)
postgresql_root_password: "{{ vault_postgresql_root_password }}"
postgresql_postgres_password: "{{ vault_postgres_user_password }}"

# Default databases and users
postgresql_databases: []
postgresql_users: []
