---
# Container Configuration
coolify_container_id: 66
coolify_hostname: coolify
coolify_domain: viljo.se
coolify_memory: 4096  # 4GB RAM recommended for production use
coolify_cores: 2
coolify_disk: 64  # 64GB for application deployments
coolify_swap: 2048
coolify_bridge: "{{ public_bridge | default('vmbr3') }}"
coolify_ip_address: 172.16.10.66
coolify_netmask: 24
coolify_ip_config: "{{ coolify_ip_address }}/{{ coolify_netmask }}"
coolify_vlan_tag: null
coolify_gateway: 172.16.10.1
coolify_dns_servers:
  - 172.16.10.1
  - 1.1.1.1

# LXC Configuration
coolify_rootfs_storage: local-lvm
coolify_unprivileged: true
coolify_start_onboot: true
coolify_features:
  nesting: 1  # Required for Docker

# Template Configuration
coolify_template_url: "{{ debian_template_url | default('http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst') }}"
coolify_template_file: "{{ debian_template_file | default('/var/lib/vz/template/cache/debian-13-standard_13.1-2_amd64.tar.zst') }}"
coolify_root_password: "{{ vault_coolify_root_password | default('') }}"
coolify_rootfs_path: "/var/lib/lxc/{{ coolify_container_id }}/rootfs"

# Docker Compose Configuration
coolify_compose_path: /opt/coolify
coolify_data_path: /data/coolify

# Coolify Application Configuration
coolify_version: 4
coolify_image: "ghcr.io/coollabsio/coolify:latest"
coolify_service_port: 8000
coolify_internal_port: 8080

# PostgreSQL Configuration (embedded in Docker Compose stack)
coolify_postgres_image: postgres:16-alpine
coolify_postgres_db: coolify
coolify_postgres_user: coolify
coolify_postgres_password: "{{ vault_coolify_postgres_password | default('') }}"

# Redis Configuration (embedded in Docker Compose stack)
coolify_redis_image: redis:7-alpine
coolify_redis_password: "{{ vault_coolify_redis_password | default('') }}"

# Soketi Configuration (real-time features)
coolify_soketi_image: quay.io/soketi/soketi:1.6-16-alpine

# Application Secrets
coolify_app_id: "{{ vault_coolify_app_id | default('') }}"
coolify_app_key: "{{ vault_coolify_app_key | default('') }}"
coolify_app_name: "Coolify"
coolify_pusher_app_id: "{{ coolify_app_id }}"
coolify_pusher_app_key: "{{ coolify_app_key }}"
coolify_pusher_app_secret: "{{ vault_coolify_pusher_app_secret | default('') }}"

# Environment Variables
coolify_env_defaults:
  APP_ENV: production
  APP_ID: "{{ coolify_app_id }}"
  APP_KEY: "{{ coolify_app_key }}"
  APP_NAME: "{{ coolify_app_name }}"
  APP_URL: "https://coolify.{{ coolify_domain }}"
  DB_DATABASE: "{{ coolify_postgres_db }}"
  DB_HOST: postgres
  DB_PASSWORD: "{{ coolify_postgres_password }}"
  DB_PORT: "5432"
  DB_USERNAME: "{{ coolify_postgres_user }}"
  PUSHER_APP_ID: "{{ coolify_pusher_app_id }}"
  PUSHER_APP_KEY: "{{ coolify_pusher_app_key }}"
  PUSHER_APP_SECRET: "{{ coolify_pusher_app_secret }}"
  PUSHER_BACKEND_HOST: soketi
  PUSHER_BACKEND_PORT: "6001"
  PUSHER_HOST: "coolify.{{ coolify_domain }}"
  PUSHER_PORT: "443"
  PUSHER_SCHEME: https
  REDIS_HOST: redis
  REDIS_PASSWORD: "{{ coolify_redis_password }}"
  REDIS_PORT: "6379"
  SSL_MODE: "off"  # Traefik handles SSL
  TZ: "{{ timezone | default('UTC') }}"

coolify_env_extra: {}
